import SideNav from "@/components/Settings/side-nav";
// import "../styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MarginWidthWrapper from "@/components/Settings/margin-width-wrapper";
import Header from "@/components/Settings/header";
import HeaderMobile from "@/components/Settings/header-mobile";
import PageWrapper from "@/components/Settings/page-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mein Account",
  // description: "Generated by create next app",
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`bg-white ${inter.className}`}>
      <div className="md:flex">
        <SideNav />
        <main className="flex-1">
          <Header />
          <MarginWidthWrapper>
            <HeaderMobile />
            <PageWrapper>{children}</PageWrapper>
          </MarginWidthWrapper>
        </main>
      </div>
    </div>
  );
}
