import { Injectable } from '@nestjs/common';
import { Conversation } from '../entities/prompt.entity';
const path = require('path');
const PDFDocument = require('pdfkit');

@Injectable()
export class DocumentExportService {
    constructor(
    ) { }

    async handlePdf(conversation: Conversation) {
        try {
            let pdfBuffer: Buffer = await this.processPdf(conversation);
            return pdfBuffer;

        } catch (error) {
            console.log(error);
            return null;
        }
    }

    private async processPdf(conversation: Conversation): Promise<Buffer> {
        const data = conversation.responses;
        const doc = new PDFDocument({
            margin: 50,
            size: 'A4',
            layout: 'landscape',
            info: {
                Title: 'Legal Document Summary',
                Author: 'Generated by German Legal Ai App',
            }
        });

        // Create a buffer to store the PDF
        const buffers: Buffer[] = [];
        doc.on('data', buffers.push.bind(buffers));

        const __dirname = path.dirname(__filename);
        doc.registerFont('TitleFont', path.join(__dirname, '../../../assets/fonts', 'Lobster-Regular.ttf'));
        doc.registerFont('BodyFont', path.join(__dirname, '../../../assets/fonts', 'OpenSans-Regular.ttf'));
        doc.registerFont('BodyFontBold', path.join(__dirname, '../../../assets/fonts', 'OpenSans-Bold.ttf'));

        let pageNumber = 1;
        function addWatermarkAndPageNumber() {
            // Ensure the watermark does not cause a page overflow
            doc.save();
            doc.image(path.join(__dirname, '../../../assets/images', 'watermark.jpg'), 0, 0, {
                width: doc.page.width,
                height: doc.page.height,
                align: 'center',
                valign: 'center',
            });
            doc.restore();
            pageNumber++;
        }

        function printPageNumber() {
            doc.fontSize(8).font('BodyFont').fillColor('black')
                .text(`Seite: ${pageNumber}`, doc.page.width - 60, doc.page.height - 20, { align: 'right' })
            pageNumber++;
        }


        // Attach event handler before content generation
        doc.on('pageAdded', addWatermarkAndPageNumber);
        addWatermarkAndPageNumber();

        doc.fontSize(28).font('TitleFont').fillColor('darkgreen')
            .text('Legal Document Compendium', { align: 'center' });
        doc.moveDown(2);

        data.forEach((item, index) => {
            if (index > 0) doc.addPage();

            const result = item.result;
            const note = item.note;

            // Attractive title for law reference
            doc.fontSize(24).font('TitleFont').fillColor('darkblue')
                .text(`${result.law} - ${result.sectionTitle}`, { align: 'center' });
            doc.moveDown(1);

            // Document title
            doc.fontSize(18).font('BodyFontBold').fillColor('black')
                .text(`Referenz:  ${item.match}`, { align: 'center' });
            doc.moveDown(2);

            // Contents
            if (item.subsection) {
                let subsection = item.subsection;

                let subsections = result.contents_string.split(/(?=\(\d+\)\s+)/);
                subsections = subsections.map(subsection => subsection.trim()).filter(subsection => subsection !== '');

                subsections.forEach(line => {
                    function isMatchingSubsection(line, subsection) {
                        const match = line.match(/^\((\d+)\)/);
                        if (match) {
                            return match[1] == subsection;
                        }
                        return false;
                    }

                    if (isMatchingSubsection(line, subsection)) {
                        doc.fontSize(12).font('BodyFontBold').fillColor('darkred')
                            .text(line, { align: 'justify' });
                    } else {
                        doc.fontSize(12).font('BodyFont').fillColor('black')
                            .text(line, { align: 'justify' });
                    }
                    doc.moveDown(0.01);

                });
            } else {
                doc.fontSize(12).font('BodyFont').fillColor('black')
                    .text(result.contents_string, { align: 'justify' });
            }

            doc.moveDown(2);

            // Note section
            if (note) {
                const noteBoxHeight = 100;
                const remainingSpace = (doc.page.height - 30) - doc.y - doc.page.margins.bottom;

                if (remainingSpace < noteBoxHeight) {

                    doc.addPage();
                }

                doc.rect(50, doc.y, doc.page.width - 100, noteBoxHeight)
                    .fillAndStroke('#f0f0f0', '#cccccc');

                doc.fontSize(12).font('BodyFontBold').fillColor('darkblue')
                    .text('Note:', 60, doc.y + 10);

                doc.fontSize(10).font('BodyFont').fillColor('black')
                    .text(note.text, 60, doc.y + 5, {
                        width: doc.page.width - 120,
                        height: noteBoxHeight - 20
                    });

                doc.moveDown(noteBoxHeight / doc.currentLineHeight());
            }

            // Source indicators in the corner
            doc.fontSize(8).font('BodyFont').fillColor('gray')
                .text(`Wahrscheinliche Quelle des Referenzdokuments:`, 50, doc.page.height - 82, { lineBreak: false })
                .text(`____________________________________________________`, 50, doc.page.height - 80, { lineBreak: false })
                .text(`Zeile: ${item.probableLine}, Seite: ${item.probablePage}`, 50, doc.page.height - 70, { lineBreak: false })
                .text(`Vollständige Zeile: ${item.fullLine_String}`, 50, doc.page.height - 60, { lineBreak: false })
                .text(`Übereinstimmung: ${item.match}`, 50, doc.page.height - 50, { lineBreak: false });

        });

        return new Promise((resolve) => {
            doc.on('end', () => {
                const pdfBuffer = Buffer.concat(buffers);
                resolve(pdfBuffer);
            });
            doc.end();
        });
    }

}
